USE [master]
GO
/****** Object:  Database [Blog]    Script Date: 9/9/2018 6:34:30 PM ******/
CREATE DATABASE [Blog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Blog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Blog.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Blog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Blog_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Blog] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Blog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Blog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Blog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Blog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Blog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Blog] SET ARITHABORT OFF 
GO
ALTER DATABASE [Blog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Blog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Blog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Blog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Blog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Blog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Blog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Blog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Blog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Blog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Blog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Blog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Blog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Blog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Blog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Blog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Blog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Blog] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Blog] SET  MULTI_USER 
GO
ALTER DATABASE [Blog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Blog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Blog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Blog] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Blog] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Blog]
GO
/****** Object:  Table [dbo].[BLOG_CONFIG]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BLOG_CONFIG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[C_KEY] [nvarchar](200) NULL,
	[VALUE] [nvarchar](1000) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MENU]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DISPLAY_NAME] [nvarchar](200) NULL,
	[DISPLAY_TYPE] [nvarchar](10) NULL,
	[SLUG] [nvarchar](100) NULL,
	[PAGE_SIZE] [int] NULL,
	[KEYWORD] [nvarchar](500) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MENU_TAG]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENU_TAG](
	[MENU_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MENU_ID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PAGE_USER]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PAGE_USER](
	[UUID] [nvarchar](50) NOT NULL,
	[USERNAME] [nvarchar](100) NOT NULL,
	[PASSWORD] [nvarchar](100) NOT NULL,
	[EMAIL] [nvarchar](200) NULL,
	[PHONE] [nvarchar](20) NULL,
	[ADDRESS] [nvarchar](500) NULL,
	[GENDER] [varchar](1) NULL,
	[COMPANY] [nvarchar](500) NULL,
	[CREATED_DATE] [date] NULL,
	[CREATED_USER] [nvarchar](100) NULL,
	[ABOUT] [nvarchar](1000) NULL,
	[FACEBOOK_PROFILE] [nvarchar](1000) NULL,
	[GPLUS_PROFILE] [nvarchar](1000) NULL,
	[INSTAGRAM_PROFILE] [nvarchar](1000) NULL,
	[TWITTER_PROFILE] [nvarchar](1000) NULL,
	[DISPLAY_NAME] [nvarchar](500) NULL,
UNIQUE NONCLUSTERED 
(
	[PASSWORD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[POST]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[POST](
	[SLUG] [nvarchar](500) NOT NULL,
	[CONTENT] [nvarchar](max) NULL,
	[CREATED_DATE] [date] NULL DEFAULT (sysdatetime()),
	[CREATED_USER] [nvarchar](100) NULL,
	[IS_ACTIVE] [varchar](1) NULL DEFAULT ('1'),
	[META_KEYWORD] [nvarchar](1000) NOT NULL,
	[META_DESC] [nvarchar](1000) NOT NULL,
	[TITLE] [nvarchar](1000) NULL,
	[VIEW_COUNT] [decimal](18, 0) NULL,
	[IMAGE_COVER] [nvarchar](1000) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MAIN_TAG] [nvarchar](100) NULL,
UNIQUE NONCLUSTERED 
(
	[SLUG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[POST_TAG]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POST_TAG](
	[TAG_ID] [int] NOT NULL,
	[POST_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_ID] ASC,
	[POST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TAG]    Script Date: 9/9/2018 6:34:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PAGE_USER] ADD  DEFAULT (sysdatetime()) FOR [CREATED_DATE]
GO
ALTER TABLE [dbo].[PAGE_USER] ADD  DEFAULT ('ADMIN') FOR [CREATED_USER]
GO
USE [master]
GO
ALTER DATABASE [Blog] SET  READ_WRITE 
GO
