//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PAGE_USER> PAGE_USER { get; set; }
        public virtual DbSet<POST_TAG> POST_TAG { get; set; }
        public virtual DbSet<TAG> TAGs { get; set; }
        public virtual DbSet<BLOG_CONFIG> BLOG_CONFIG { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MENU_TAG> MENU_TAG { get; set; }
        public virtual DbSet<POST> POSTs { get; set; }
    }
}
