//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string DISPLAY_TYPE { get; set; }
        public string SLUG { get; set; }
        public Nullable<int> PAGE_SIZE { get; set; }
        public string KEYWORD { get; set; }
    }
}
