//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_USER
    {
        public string UUID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string GENDER { get; set; }
        public string COMPANY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public string ABOUT { get; set; }
        public string FACEBOOK_PROFILE { get; set; }
        public string GPLUS_PROFILE { get; set; }
        public string INSTAGRAM_PROFILE { get; set; }
        public string TWITTER_PROFILE { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string IMAGE_PROFILE { get; set; }
    }
}
