//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public string SLUG { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public string IS_ACTIVE { get; set; }
        public string META_KEYWORD { get; set; }
        public string META_DESC { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> VIEW_COUNT { get; set; }
        public string IMAGE_COVER { get; set; }
        public int ID { get; set; }
        public string MAIN_TAG { get; set; }
    }
}
